# Generated by Django 5.2.4 on 2025-10-17 09:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('room_name', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique room_name for WS upgrade and also unique identifier for this chat.', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_message', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GatekeeperLogReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_ok', models.BooleanField(help_text='Was the action (Allow/ Block) appropriate?')),
                ('rating', models.SmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], help_text='How good was the reason provided?')),
                ('comment', models.TextField(blank=True, help_text='Any additional comments by the reviewer', null=True)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GatekeeperLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked_at', models.CharField(blank=True, help_text='Which layer blocked this message?', max_length=30, null=True)),
                ('reason', models.TextField(help_text='Why was this query blocked or allowed?', verbose_name='reason')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=50)),
                ('content', models.TextField(verbose_name='message')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UsagePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy', models.JSONField()),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
